#---Banned substrings---
#Note: some words are intentionally mispelled

#intercourse
- fuck
- sex
- bang
- screw

#masturbation
- jack
- wank
- jerk
- fap

#body parts
- vagina
- vulva
- cunt
- twat
- clit

- penis
- dick
- cock
- prick

- ass
- arse
- rectum
- anus
- butt

#excretions
- sperm
- semen
- jizz
- cum
- come

- shit
- poop
- dump

- piss
- urin
- pee

- douch

#slurs
- bastard
- fag
- kike
- gook
- chink
- homo
- nig

#others
- pedo
- hitler
- castro
- red rocket
- erik

#miscellany - might not be obscene, but I'm not taking chances
- load
- sack
- ball
- mom
- mother

