#---Banned substrings---

#intercourse
- fuck
- sex

#body parts
- vagina
- vulva
- cunt
- twat

- penis
- dick
- cock
- prick

- ass
- arse
- rectum
- anus
- butt

#excretions
- sperm
- semen
- jizz
- cum
- come

- shit
- poop
- dump

- piss
- urine
- pee


#slurs
- bastard
- fag
- kike
- gook
- chink
- homo

#miscellany - might not be obscene, but I'm not taking chances
- load
- sack
- ball
