
test:
  adapter: postgresql
  encoding: unicode
  database: zoobit_test
  pool: 5
  username: postgres
  password:

development:
  production:
  adapter: postgresql
  encoding: unicode
  database: zoobit_development
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: zoobit_production
  pool: 5
  username: postgres
  password:
